INSERT INTO emis.news_items (
	id,
	source_id,
	source_item_id,
	url,
	title,
	summary,
	body,
	language,
	published_at,
	country_code,
	region,
	news_type,
	importance,
	geom,
	is_manual,
	meta
)
VALUES
	(
		'00000000-0000-0000-0000-000000000201',
		'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
		'rss-001',
		'https://example.com/news/port-001',
		'Логистическая активность в районе Новороссийского порта',
		'Демо-новость для стартового списка.',
		'Короткий seed-текст для демонстрации карточки новости и работы связей.',
		'ru',
		'2026-03-10T09:00:00Z',
		'RU',
		'Краснодарский край',
		'logistics',
		3,
		ST_SetSRID(ST_GeomFromText('POINT(37.7700 44.7240)'), 4326),
		false,
		'{"seed":true}'::jsonb
	),
	(
		'00000000-0000-0000-0000-000000000202',
		'cccccccc-cccc-cccc-cccc-cccccccccccc',
		'tg-002',
		'https://t.me/example/2',
		'Обсуждение поставок через LNG терминал в Турции',
		'Вторая демо-новость с внешним объектом.',
		'Seed-запись нужна для проверки многообъектных связей и карты.',
		'ru',
		'2026-03-11T11:30:00Z',
		'TR',
		'Измир',
		'market',
		2,
		ST_SetSRID(ST_GeomFromText('POINT(26.9620 38.7990)'), 4326),
		false,
		'{"seed":true}'::jsonb
	),
	(
		'00000000-0000-0000-0000-000000000203',
		'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
		'manual-003',
		NULL,
		'Ручная заметка по объектам Краснодарского края',
		'Демо manual news item.',
		'Эта запись показывает, что manual-источник тоже поддерживается уже на seed уровне.',
		'ru',
		'2026-03-12T07:45:00Z',
		'RU',
		'Краснодарский край',
		'incident',
		4,
		NULL,
		true,
		'{"seed":true,"manual":true}'::jsonb
	)
ON CONFLICT (id) DO UPDATE
SET
	source_id = EXCLUDED.source_id,
	source_item_id = EXCLUDED.source_item_id,
	url = EXCLUDED.url,
	title = EXCLUDED.title,
	summary = EXCLUDED.summary,
	body = EXCLUDED.body,
	language = EXCLUDED.language,
	published_at = EXCLUDED.published_at,
	country_code = EXCLUDED.country_code,
	region = EXCLUDED.region,
	news_type = EXCLUDED.news_type,
	importance = EXCLUDED.importance,
	geom = EXCLUDED.geom,
	is_manual = EXCLUDED.is_manual,
	meta = EXCLUDED.meta,
	updated_at = now();
